// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAugmentRecommendations(arg1) {
  return window['go']['main']['App']['GetAugmentRecommendations'](arg1);
}

export function GetBuildRecommendation(arg1) {
  return window['go']['main']['App']['GetBuildRecommendation'](arg1);
}

export function GetChampionImages(arg1) {
  return window['go']['main']['App']['GetChampionImages'](arg1);
}

export function GetCurrentPhase() {
  return window['go']['main']['App']['GetCurrentPhase']();
}

export function GetEnemyTeamStats() {
  return window['go']['main']['App']['GetEnemyTeamStats']();
}

export function GetItemImageURL(arg1) {
  return window['go']['main']['App']['GetItemImageURL'](arg1);
}

export function GetMyTeamStats() {
  return window['go']['main']['App']['GetMyTeamStats']();
}
