// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {data} from '../models';
import {main} from '../models';

export function GetAugmentRecommendations(arg1:number):Promise<Array<data.HeroAugmentStat>>;

export function GetBuildRecommendation(arg1:number):Promise<data.Build>;

export function GetChampionImages(arg1:Array<number>):Promise<Array<main.ChampionImage>>;

export function GetCurrentPhase():Promise<string>;

export function GetEnemyTeamStats():Promise<Array<main.TeamMemberStats>>;

export function GetItemImageURL(arg1:number):Promise<string>;

export function GetMyTeamStats():Promise<Array<main.TeamMemberStats>>;
